baseURL = "https://mk-619.github.io/gadgelog/"
languageCode = "ja-jp"
title = "gadgelog"
theme = "ananke"

[params]
  description = "gadgelogとは，学びと記録のために，日々を綴るガジェット好きの備忘録です．"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
   name = "gadget"
    url = "/gadget/"
    weight = 10

  [[menu.main]]
    name = "Study"
    url = "/study/"
    weight = 20

  [[menu.main]]
    name = "Record"
    url = "/record/"
    weight = 30

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 40